{% set version = "0.9.3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rzmq
  version: {{ version|replace("-", "_") }}

source:
  fn: rzmq_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rzmq_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rzmq/rzmq_{{ version }}.tar.gz


  sha256: ab6f6da1fcd0c11003517a21bd85f5c56495e6926542db3fb320f3901f292b13

build:
  merge_build_host: True  # [win]
  number: 1

  rpaths:
    - lib/R/lib/
    - lib/
  skip: True  # [win32]


requirements:
  build:
    - posix                # [win]
    - pkg-config           # [unix]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - zeromq               # [not win]
    - {{native}}zeromq     # [win]

  run:
    - r-base
    - zeromq               # [not win]
    - {{native}}zeromq     # [win]

test:
  commands:
    - $R -e "library('rzmq')"  # [not win]
    - "\"%R%\" -e \"library('rzmq')\""  # [win]



about:
  home: http://github.com/ropensci/rzmq
  license: GPL-3
  summary: Interface to the 'ZeroMQ' lightweight messaging kernel (see <http://www.zeromq.org/>
    for more information).
  license_family: GPL3



extra:
  recipe-maintainers:
    - croth1
