{% set version = "0.9.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rzmq
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rzmq_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rzmq/rzmq_{{ version }}.tar.gz
  sha256: 5f47b67b75fd4a230780406f7a55a3708ce8c014cff755a809a6bfa1a6925a45

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - zeromq                     # [not win]
    - {{ native }}zeromq           # [win]
  run:
    - r-base
    - zeromq                     # [not win]
    - {{ native }}zeromq           # [win]
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('rzmq')"           # [not win]
    - "\"%R%\" -e \"library('rzmq')\""  # [win]

about:
  home: http://github.com/ropensci/rzmq#readme (devel) http://www.zeromq.org (upstream)
  license: GPL-3
  summary: Interface to the 'ZeroMQ' lightweight messaging kernel (see <http://www.zeromq.org/>
    for more information).
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - croth1
# Package: rzmq
# Title: R Bindings for 'ZeroMQ'
# Version: 0.9.6
# Authors@R: c( person("Whit", "Armstrong", , "armstrong.whit@gmail.com", role = "aut"), person("Michael", "Schubert", role = "ctb"), person("Jeroen", "Ooms", , "jeroen@berkeley.edu", role = c("aut", "cre")))
# Description: Interface to the 'ZeroMQ' lightweight messaging kernel (see <http://www.zeromq.org/> for more information).
# License: GPL-3
# Depends: R (>= 3.1.0)
# SystemRequirements: ZeroMQ >= 3.0.0: libzmq3-dev (deb) or zeromq-devel (rpm)
# URL: http://github.com/ropensci/rzmq#readme (devel) http://www.zeromq.org (upstream)
# BugReports: http://github.com/ropensci/rzmq/issues
# NeedsCompilation: yes
# Packaged: 2019-03-01 17:07:50 UTC; jeroen
# Author: Whit Armstrong [aut], Michael Schubert [ctb], Jeroen Ooms [aut, cre]
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2019-03-01 21:50:09 UTC
