{% set version = "0.9.15" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rzmq
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rzmq_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rzmq/rzmq_{{ version }}.tar.gz
  sha256: 4e56e95d5ea4ed15a362cf9cb46010867e1724c12cec1255ea5018facc247100

build:
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - zeromq                       # [not win]
    - zeromq           # [win]
  run:
    - r-base
    - zeromq                       # [not win]
    - zeromq           # [win]

test:
  source_files:
    - tests/
  commands:
    - $R -e "library('rzmq')"           # [not win]
    - $R -f tests/poll.R                # [not win]
    - "\"%R%\" -e \"library('rzmq')\""  # [win]
    - "\"%R%\" -f tests/poll.R"         # [win]

about:
  home: http://www.zeromq.org
  dev_url: http://github.com/ropensci/rzmq
  license: GPL-3.0-only
  summary: Interface to the 'ZeroMQ' lightweight messaging kernel (see <http://www.zeromq.org/> for more information).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - croth1
