{% set version = '0.9.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rzmq
  version: {{ version|replace("-", "_") }}

source:
  fn: rzmq_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rzmq_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rzmq/rzmq_{{ version }}.tar.gz
  sha256: 03fbda756d823c11fba359b94a6213c3440e61973331668eaac35779717f73ad

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - zeromq                     # [not win]
    - {{native}}zeromq           # [win]

  run:
    - r-base
    - zeromq                     # [not win]
    - {{native}}zeromq           # [win]
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('rzmq')"           # [not win]
    - "\"%R%\" -e \"library('rzmq')\""  # [win]

about:
  home: http://github.com/ropensci/rzmq
  license: GPL-3
  summary: Interface to the 'ZeroMQ' lightweight messaging kernel (see <http://www.zeromq.org/>
    for more information).
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - croth1
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
