appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: J6L3xiyAu85Ra7cBEGhRfJUe3tGyDFvRF5TJpSrV7DPVzuys+RQn4S4aAHvLbxdvcOdM16+V7ETVuS4cJEHsww5uofDXRVbs5wBThPksGNiw+U+HuBZ99okBjiks9+2LbmnbLDT27MCfnDyFI1/k4CidjIhNXVGrHQcO0T9iEocc3tZ6HVNp3NFauvL5M1iBqWebToqunnzdFhmyDQHOek7tqv7QFLXbY1cDl2OlNTuZJtkrZ9q1JI7tfhTeQzQju953KQYvCCRTeVjkFWMREzgEwXxiBxSjQVqU45fYGkvqnhAQhYuXbPzRdCwOwCAHlk9pKvITbfY5SOAbsK5Bt4F0aTTLZPilmVsRlZiL9L35xObf4OxDevXX1Iz9wCLJZDZP3yvEdP1hrY9E3j+rOLkcykWHQVpssqoCGEn0oR6a8PyF9tYlQoEfvJDAHS6SOc1SF2Gp+zDnVbFz0AxkbX79YuKJEmcdntmlPLpKuT/ZXyabFuzy4coq3BDn3+8uDV7IJ+b/PMZNJFQNrPtIDGDHPusTRH5CBFsTrmXyS5kCBV+XXJxFWOtq7RlW8sztriRi9UvlQvuJGMIZ4O1ob10BygPHIF22xESXWxkZao1tOLWh2yE9ItiXg4d9zFJIo2JfM1EftoBTV6HhBjN2pjJAzfw97PeLzqUwgIq1am4=}
